apiVersion: v1
kind: Secret
metadata:
  name: redpanda-credentials
type: Opaque
stringData:
  SUPER_USER: "cool_admin:tempPassword6512"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-bootstrap
data:
  bootstrap.yaml: |
    enable_sasl: true
    superusers:
      - cool_admin
    sasl_mechanisms:
      - SCRAM
      - PLAIN

---

apiVersion: v1
kind: Pod
metadata:
  name: redpanda-seed-1
  annotations:
    ad.datadoghq.com/my-app.logs: '[{"source": "infra", "service": "redpanda-seed-1"}]'
spec:
  restartPolicy: Always
  containers:
    - name: redpanda-seed-1
      image: docker.io/redpandadata/redpanda:v25.3.7
      resources:
        requests:
          cpu: "3"
          memory: "6Gi"
        limits:
          cpu: "3"
          memory: "6Gi"
      volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/redpanda/data
        - name: bootstrap-config
          mountPath: /etc/redpanda/.bootstrap.yaml
          subPath: bootstrap.yaml
      ports:
        - containerPort: 19092
          hostPort: 19092
          hostIP: 10.1.0.11
        - containerPort: 33145
          hostPort: 33145
          hostIP: 10.1.0.11
      env:
        - name: RP_BOOTSTRAP_USER
          valueFrom:
            secretKeyRef:
              name: redpanda-credentials
              key: SUPER_USER
      command:
        - /usr/bin/rpk
      args:
        - redpanda
        - start
        - --kafka-addr
        - 0.0.0.0:19092
        - --advertise-kafka-addr
        - 10.1.0.11:19092
        - --rpc-addr
        - 0.0.0.0:33145
        - --advertise-rpc-addr
        - 10.1.0.11:33145
        - --seeds
        - 10.1.0.15:33145

  volumes:
    - name: kafka-storage
      persistentVolumeClaim:
        claimName: kafka-storage
    - name: bootstrap-config
      configMap:
        name: redpanda-bootstrap
