version: 1
name: mongo

connection: connection.json.mako

image:
  registry: local
  path: infra_depence/mongo
  version: 7.0.18-rc0

roles:
  member:
    ports:
      - number: 27017
        protocol: tcp
        zone: internal

templates:
  pod:
    path: mongo-instance.yml.mako
    dest: /home/userapp/mongo.yml
    owner: userapp
    mode: "644"
